-- Run this script in the Supabase SQL Editor

-- 1. Create Users Table
create table users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  role text not null default 'student',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Subjects Table
create table subjects (
  id bigint generated by default as identity primary key,
  name text unique not null,
  semester int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Materials Table
create table materials (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade not null,
  title text not null,
  type text not null check (type in ('theory', 'lab')),
  file_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security (RLS) - Optional for now, but good practice
alter table users enable row level security;
alter table subjects enable row level security;
alter table materials enable row level security;

-- 5. Create Policies (Public Access for prototype simplicity)
create policy "Allow all access" on users for all using (true);
create policy "Allow all access" on subjects for all using (true);
create policy "Allow all access" on materials for all using (true);
